<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7xaxkr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7xaxkr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerL7xaxkr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerL7xaxkr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerL7xaxkr\appProdProjectContainer([
    'container.build_hash' => 'L7xaxkr',
    'container.build_id' => 'a452e763',
    'container.build_time' => 1672337410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL7xaxkr');
